### ISSUE TITLE
evaluate error with sympy expression

### ISSUE THREAD

**Issue by bknight1** [underworldcode/underworld3-archive#111]
Not sure if it's the sympy version or something has changed with recent updates:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[11], line 12
      9 adv_diff.add_dirichlet_bc(0.0, "Upper")
     11 with meshball.access(t_0, t_soln):
---> 12     t_0.data[...] = uw.function.evaluate(init_t, t_0.coords).reshape(-1, 1)
     13     t_soln.data[...] = t_0.data[...]

File ~/Documents/Research/Github/underworld3/underworld3/function/_function.pyx:410, in underworld3.function._function.evaluate()

File <lambdifygenerated-1>:7, in _lambdifygenerated(_Dummy_24, _Dummy_25)
      2     [Dummy_23, Dummy_22] = _Dummy_24
      3     [] = _Dummy_25
      4     return (  # Not supported in Python with numpy:
      5   # BaseScalar
      6   # BaseScalar
----> 7 -2.0*sqrt(N0.x**2 + N0.y**2) + 0.01*sin(6.28318530717959*sqrt(N0.x**2 + N0.y**2) - 3.14159265358979)*sin(15.0*arctan2(N0.y + 1.0e-5, N0.x + 1.0e-5)) + 2.0)

NameError: name 'N0' is not defined
```
from this examples: [Ex_Convection_Cylinder.py](https://github.com/underworldcode/underworld3/blob/ViscoelasticPlastic-v1/Jupyterbook/Notebooks/Examples-Convection/Ex_Convection_Cylinder.py)

**Comment by lmoresi** [comment]
This is a problem with multiple coordinate systems - and maybe we should just default to Cartesian - but arises with pure functions that have no mesh attached. We can't evaluate the function unless we know what the unit vectors refer to. So, evaluate also takes a third argument which is the basis. Easiest way is to add mesh.N as that argument.

Happy to receive comments on this ... 

It does not always appear because if there is a mesh variable in there somewhere then the evaluate routines grab mesh.N from that.

**Comment by bknight1** [comment]
My fault, forgot this had been updated since I'd last used the evaluate function.
