### ISSUE TITLE
Hex v. Simplex

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/underworld3-archive#41]
I have added a number of hex-based mesh types via gmsh which also gives structured tetrahedra that align with the hexes (for free - just don't recombine them into hexes). There are multiple problems with hex meshes not solving properly and not interpolating. 

This is a shame because the hex-based cubed sphere should have a fast / analytic element-finding strategy that has no need for brute force and would therefore solve many of our other problems.

See Regional Spherical notebook for an example of how this goes wrong.

**Comment by jmansour** [comment]
Are you talking about `Ex_Stokes_RegionalCap.py`?  Also, can you be a bit more specific about your issues as I'm unsure if I'm encoutering the same onces.  I did have to drop the viz routines as they were seg faulting, but the issue didn't appear to be related to interpolation. 

Note that in my PR there are some improvements for the interpolations. Also, PETSc (as of 3.16) includes an implementation for mesh hashing in 3D, although there are still some 3.16 compat issues that require investigation. However, once the compatibility problems have been resolved, there should no longer be any need to fall back to naive brute force.  The element-finding still isn't particularly fast, but it is now similar to the solve time instead of orders of magnitude slower.

**Comment by lmoresi** [comment]
For all "deformed" hex meshes, the solver simply goes off for a bit of a wander and returns no result. Stokes and Poisson.

Hexes:
  0 SNES Function norm 44.9854 
  1 SNES Function norm 44.9854 
  2 SNES Function norm 44.9854 
  3 SNES Function norm 44.9854 
  4 SNES Function norm 44.9854 
Nonlinear solve did not converge due to DIVERGED_LINE_SEARCH iterations 4

Tets:

  0 SNES Function norm 29.7253 
  1 SNES Function norm 0.0452809 
  2 SNES Function norm 5.11236e-05 
Nonlinear solve converged due to CONVERGED_FNORM_RELATIVE iterations 2

All I am doing in the code is to set or not set the simplex option. I suspect this is something to do with how we read the meshes into DMPlex. @rbeucher ... we should try this via the .msh file to see what it produces.

**Comment by knepley** [comment]
Note that you can check meshes by giving -dm_plex_check_all

**Comment by lmoresi** [comment]
Ah ... that's handy. They are both broken !!

There is obviously something going on in our workflow from gmsh to dmplex and I think we will stop trying to be clever and just use the PETSc built-in. 

You'd think we would have learned that by now.

**Comment by knepley** [comment]
If there is anything that I do not get quite right, or just as you want, for the Gmsh conversion, let me know. We are currently going over it for PyLith so that we can generate meshes with the correct things marked for boundary conditions.

**Comment by lmoresi** [comment]
I'm going to close this - we have the meshing under control thanks to @rbeucher and probably fixes in the gmesh reader. Any other problems, we should raise more specific issues.
