### ISSUE TITLE
Petsc 3.16 Compatibility

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld3-archive#44]
Just adding some notes here. 

The final test in `Ex_Poisson_Cartesian.py` fails for `PETSc 3.16.0`. In particular, this test sets an aux variable to define the thermal conductivity, and indeed breaking in during runtime shows that the `dmAux` values (obtained via `petsc_a[1]` for example) are garbage.

A quick test suggested that this was also the case for the Stokes based models.  

These calls might need to be re-examined:
https://github.com/underworldcode/underworld3/blob/master/underworld3/systems/poisson.pyx#L198
https://github.com/underworldcode/underworld3/blob/master/underworld3/systems/stokes.pyx#L457

**Comment by knepley** [comment]
@jmansour Yes, I finally made an official interface for them to be set: https://petsc.org/main/docs/manualpages/DM/DMSetAuxiliaryVec.html . To get the name effect, set NULL for the label, and make sure the dmAux is the dm for the vec you pass in.

**Comment by julesghub** [comment]
As of ee2d355 we are petsc 3.16 compatible.
Thanks @knepley for the DMSetAuxiliaryVec info.

The error @jmansour  noted was due to `DMAddBoundary()` requiring a `name` argument. Interestingly the petsc c code check for a valid name pointer was triggering an error message but petsc4py was blocking that error from causing a standard PetscError TraceBack event. @knepley any ideas why petsc4py would change the standard petsc error reporting?

**Comment by knepley** [comment]
First, `DMAddBoundary()` now takes the label directly (https://petsc.org/main/docs/manualpages/DM/DMAddBoundary.html). I changed this because exactly this situation kept happening. Also, in different MG levels, the labels changes but the name is the same, which messed the old thing up.

Second, I don't think we changed the way petsc4py does errors. However, I know Firedrake has a problem with the default signal handler. Can you check if `handler = PETSc.Sys.popErrorHandler()` before the run gets you the stack trace.

**Comment by julesghub** [comment]
You're right @knepley, calling `PETSc.Sys.popErrorHandler()` before the error gives a proper stack trace with Petsc error msg.
For now I'll put this our initialisation code - we need the stack trace for development. 
Is there an issue for this issue that I can follow?

**Comment by knepley** [comment]
I don't think we have one. We put in a signal handler because that gives the correct behavior from C, but if you want a Python stack, I guess you need to get rid of it. This probably needs to go in the documentation. I will make an issue and add you.

**Comment by knepley** [comment]
Here is the issue: https://gitlab.com/petsc/petsc/-/issues/1066

**Comment by julesghub** [comment]
Cheers Matt! That's super helpful.
