### ISSUE TITLE
Issues with examples

### ISSUE THREAD

**Issue by bknight1** [underworldcode/underworld3-archive#84]
PETSc4py & PETSc version - '3.17.4'

Found a few issues in the Jupyterbook/Notebooks/ examples, these were the issues I wasn't able to quickly fix:

- AttributeError: 'petsc4py.PETSc.DMPlex' object has no attribute 'getMinRadius' when seting up advDiffusion equation, stokes.estimate_dt() etc. 
```
File ~/Documents/Research/Codes/underworld3-development/underworld3/discretisation.pyx:603, in underworld3.discretisation.Mesh.get_min_radius()

AttributeError: 'petsc4py.PETSc.DMPlex' object has no attribute 'getMinRadius'
```

- Navier-Stokes examples - issue with the setup terms:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [13], in <cell line: 1>()
----> 1 navier_stokes.solve(timestep=1.0)  # Stokes-like initial flow
      2 nodal_vorticity_from_v.solve()

File ~/Documents/Research/Codes/underworld3-development/underworld3/systems/solvers.py:1313, in SNES_NavierStokes_Swarm.solve(self, zero_init_guess, timestep, _force_u_star_projection, _force_setup)
   1310     self.delta_t = timestep    # this will force an initialisation because the functions need to be updated
   1312 if (not self.is_setup) or _force_setup:
-> 1313     self._setup_terms()
   1315 # Make sure we update the projection of the swarm variable if requested
   1316 # But, this can break down on the first solve if there are constraints and bcs
   1317 # (we might want to use v_star for checkpointing though)
   1319 if self.projection and (not self.first_solve or _force_u_star_projection):

File ~/Documents/Research/Codes/underworld3-development/underworld3/systems/solvers.py:1340, in SNES_NavierStokes_Swarm._setup_terms(self)
   1338 if self.projection:
   1339     self._u_star_projector.bcs = self.bcs
-> 1340     self._u_star_projector._setup_terms()
   1342 super()._setup_terms()

File ~/Documents/Research/Codes/underworld3-development/underworld3/systems/generic_solvers.pyx:556, in underworld3.systems.generic_solvers.SNES_Vector._setup_terms()

File ~/Documents/Research/Codes/underworld3-development/underworld3/systems/solvers.py:635, in SNES_Vector_Projection.projection_problem_description(self)
    627 N   = self.mesh.N
    629 # residual terms - defines the problem:
    630 # solve for a best fit to the continuous mesh
    631 # variable given the values in self.function 
    632 # F0 is left in place for the user to inject 
    633 # non-linear constraints if required
--> 635 self._f0 = self.F0 + (self.u.sym - self.uw_function) * self.uw_weighting_function
    637 # F1 is left in the users control ... e.g to add other gradient constraints to the stiffness matrix
    639 E = 0.5 * (sympy.Matrix(self._L) + sympy.Matrix(self._L).T) # ??

File ~/Documents/Research/PyVenv/UW3/lib/python3.9/site-packages/sympy/core/decorators.py:105, in call_highest_priority.<locals>.priority_decorator.<locals>.binary_op_wrapper(self, other)
    103         f = getattr(other, method_name, None)
    104         if f is not None:
--> 105             return f(self)
    106 return func(self, other)

File ~/Documents/Research/PyVenv/UW3/lib/python3.9/site-packages/sympy/core/decorators.py:106, in call_highest_priority.<locals>.priority_decorator.<locals>.binary_op_wrapper(self, other)
    104         if f is not None:
    105             return f(self)
--> 106 return func(self, other)

File ~/Documents/Research/PyVenv/UW3/lib/python3.9/site-packages/sympy/vector/basisdependent.py:35, in BasisDependent.__rsub__(self, other)
     33 @call_highest_priority('__sub__')
     34 def __rsub__(self, other):
---> 35     return self._add_func(other, -self)

File ~/Documents/Research/PyVenv/UW3/lib/python3.9/site-packages/sympy/vector/vector.py:411, in VectorAdd.__new__(cls, *args, **options)
    410 def __new__(cls, *args, **options):
--> 411     obj = BasisDependentAdd.__new__(cls, *args, **options)
    412     return obj

File ~/Documents/Research/PyVenv/UW3/lib/python3.9/site-packages/sympy/vector/basisdependent.py:195, in BasisDependentAdd.__new__(cls, *args, **options)
    193         arg = cls._add_func(*(arg.args))
    194     else:
--> 195         raise TypeError(str(arg) +
    196                         " cannot be interpreted correctly")
    197 # If argument is zero, ignore
    198 if arg == cls.zero:

TypeError: Matrix([[uStar1_{ 0 }(N.x, N.y), uStar1_{ 1 }(N.x, N.y)]]) cannot be interpreted correctly
```

Cheers

**Comment by lmoresi** [comment]
Ok - I’m fixing a lot of these on the constitute models branch.

Sent from my iPhone

On 17 Aug 2022, at 4:01 pm, Ben Knight ***@***.***> wrote:

﻿

PETSc4py & PETSc version - '3.17.4'

Found a few issues in the Jupyterbook/Notebooks/ examples, these were the issues I wasn't able to quickly fix:

  *   AttributeError: 'petsc4py.PETSc.DMPlex' object has no attribute 'getMinRadius' when seting up advDiffusion equation, stokes.estimate_dt() etc.

File ~/Documents/Research/Codes/underworld3-development/underworld3/discretisation.pyx:603, in underworld3.discretisation.Mesh.get_min_radius()

AttributeError: 'petsc4py.PETSc.DMPlex' object has no attribute 'getMinRadius'


  *   Navier-Stokes examples - issue with the setup terms:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [13], in <cell line: 1>()
----> 1 navier_stokes.solve(timestep=1.0)  # Stokes-like initial flow
      2 nodal_vorticity_from_v.solve()

File ~/Documents/Research/Codes/underworld3-development/underworld3/systems/solvers.py:1313, in SNES_NavierStokes_Swarm.solve(self, zero_init_guess, timestep, _force_u_star_projection, _force_setup)
   1310     self.delta_t = timestep    # this will force an initialisation because the functions need to be updated
   1312 if (not self.is_setup) or _force_setup:
-> 1313     self._setup_terms()
   1315 # Make sure we update the projection of the swarm variable if requested
   1316 # But, this can break down on the first solve if there are constraints and bcs
   1317 # (we might want to use v_star for checkpointing though)
   1319 if self.projection and (not self.first_solve or _force_u_star_projection):

File ~/Documents/Research/Codes/underworld3-development/underworld3/systems/solvers.py:1340, in SNES_NavierStokes_Swarm._setup_terms(self)
   1338 if self.projection:
   1339     self._u_star_projector.bcs = self.bcs
-> 1340     self._u_star_projector._setup_terms()
   1342 super()._setup_terms()

File ~/Documents/Research/Codes/underworld3-development/underworld3/systems/generic_solvers.pyx:556, in underworld3.systems.generic_solvers.SNES_Vector._setup_terms()

File ~/Documents/Research/Codes/underworld3-development/underworld3/systems/solvers.py:635, in SNES_Vector_Projection.projection_problem_description(self)
    627 N   = self.mesh.N
    629 # residual terms - defines the problem:
    630 # solve for a best fit to the continuous mesh
    631 # variable given the values in self.function
    632 # F0 is left in place for the user to inject
    633 # non-linear constraints if required
--> 635 self._f0 = self.F0 + (self.u.sym - self.uw_function) * self.uw_weighting_function
    637 # F1 is left in the users control ... e.g to add other gradient constraints to the stiffness matrix
    639 E = 0.5 * (sympy.Matrix(self._L) + sympy.Matrix(self._L).T) # ??

File ~/Documents/Research/PyVenv/UW3/lib/python3.9/site-packages/sympy/core/decorators.py:105, in call_highest_priority.<locals>.priority_decorator.<locals>.binary_op_wrapper(self, other)
    103         f = getattr(other, method_name, None)
    104         if f is not None:
--> 105             return f(self)
    106 return func(self, other)

File ~/Documents/Research/PyVenv/UW3/lib/python3.9/site-packages/sympy/core/decorators.py:106, in call_highest_priority.<locals>.priority_decorator.<locals>.binary_op_wrapper(self, other)
    104         if f is not None:
    105             return f(self)
--> 106 return func(self, other)

File ~/Documents/Research/PyVenv/UW3/lib/python3.9/site-packages/sympy/vector/basisdependent.py:35, in BasisDependent.__rsub__(self, other)
     33 @call_highest_priority('__sub__')
     34 def __rsub__(self, other):
---> 35     return self._add_func(other, -self)

File ~/Documents/Research/PyVenv/UW3/lib/python3.9/site-packages/sympy/vector/vector.py:411, in VectorAdd.__new__(cls, *args, **options)
    410 def __new__(cls, *args, **options):
--> 411     obj = BasisDependentAdd.__new__(cls, *args, **options)
    412     return obj

File ~/Documents/Research/PyVenv/UW3/lib/python3.9/site-packages/sympy/vector/basisdependent.py:195, in BasisDependentAdd.__new__(cls, *args, **options)
    193         arg = cls._add_func(*(arg.args))
    194     else:
--> 195         raise TypeError(str(arg) +
    196                         " cannot be interpreted correctly")
    197 # If argument is zero, ignore
    198 if arg == cls.zero:

TypeError: Matrix([[uStar1_{ 0 }(N.x, N.y), uStar1_{ 1 }(N.x, N.y)]]) cannot be interpreted correctly


Cheers
